import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";

import Navbar from "@/components/layouts/navbar";
import Footer from "@/components/layouts/footer";
import ClientSessionProvider from "@/components/layouts/ClientSessionProvided"; // Import your Client Session Provider

const poppin = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Federal Forecasting",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${poppin.className} bg-[#F2F2F2]`}>
                <ClientSessionProvider> 
                    <Navbar />
                    {children}
                    <Footer />
                </ClientSessionProvider>
            </body>
        </html>
    );
}
